# -*- coding: utf-8 -*-
"""Challenge Agente IA

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vBuGepZDNS34vnfsz8KtumvoliqEQAPh
"""

!pip uninstall -y pillow
!pip -q install pillow==9.5.0 pdfplumber sentence-transformers faiss-cpu transformers accelerate torch

import sys
!pip install --upgrade pillow>=10.1 --quiet
# Restart kernel to ensure changes take effect if necessary

import re
import faiss
import pdfplumber
import numpy as np

from google.colab import files
from sentence_transformers import SentenceTransformer
from transformers import pipeline

print("Selecione um documento PDF.")

uploaded = files.upload()

NOME_PDF = list(uploaded.keys())[0]

print(f"Documento carregado: {NOME_PDF}")

def limpar_texto(texto):

    texto = re.sub(r"\n+", "\n", texto)
    texto = re.sub(r"[ \t]+", " ", texto)
    texto = re.sub(r"\s{2,}", " ", texto)

    return texto.strip()


def extrair_paginas(pdf_path):

    paginas = []

    with pdfplumber.open(pdf_path) as pdf:

        for numero, pagina in enumerate(pdf.pages, start=1):

            texto = pagina.extract_text()

            if texto:

                paginas.append({
                    "pagina": numero,
                    "texto": limpar_texto(texto)
                })

    return paginas


paginas = extrair_paginas(NOME_PDF)

print(f"{len(paginas)} páginas lidas.")

def criar_chunks_paginas(paginas,
                         tamanho=900,
                         sobreposicao_palavras=60):

    chunks = []

    for item in paginas:

        palavras = item["texto"].split()

        atual = []
        contador = 0

        for palavra in palavras:

            atual.append(palavra)
            contador += len(palavra) + 1

            if contador >= tamanho:

                chunks.append({
                    "pagina": item["pagina"],
                    "texto": " ".join(atual)
                })

                atual = atual[-sobreposicao_palavras:]
                contador = sum(len(p)+1 for p in atual)

        if atual:

            chunks.append({
                "pagina": item["pagina"],
                "texto": " ".join(atual)
            })

    return chunks


chunks = criar_chunks_paginas(paginas)

print(f"{len(chunks)} trechos criados.")

print("Carregando modelo de embeddings...")

modelo_embedding = SentenceTransformer(
    "sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2"
)

textos_chunks = [c["texto"] for c in chunks]

embeddings = modelo_embedding.encode(
    textos_chunks,
    convert_to_numpy=True,
    show_progress_bar=True
)

faiss.normalize_L2(embeddings)

index = faiss.IndexFlatIP(embeddings.shape[1])

index.add(embeddings)

print("Índice vetorial criado.")

print("Carregando modelo de IA...")

llm = pipeline(
    "text-generation",
    model="google/flan-t5-base",
    max_new_tokens=256,
    truncation=True
)

def buscar_contexto(pergunta,
                    k=5,
                    limiar=0.32):

    pergunta_emb = modelo_embedding.encode(
        [pergunta],
        convert_to_numpy=True
    )

    faiss.normalize_L2(pergunta_emb)

    scores, ids = index.search(pergunta_emb, k)

    resultados = []

    for score, idx in zip(scores[0], ids[0]):

        if score >= limiar:

            resultados.append({
                "pagina": chunks[idx]["pagina"],
                "texto": chunks[idx]["texto"],
                "score": float(score)
            })

    return resultados

def responder(pergunta):

    resultados = buscar_contexto(pergunta)

    if len(resultados) == 0:
        return {
            "resposta": "Não encontrei essa informação no documento.",
            "paginas": []
        }

    contexto = ""

    paginas_utilizadas = []

    for r in resultados:

        paginas_utilizadas.append(r["pagina"])

        contexto += f"\n[PÁGINA {r['pagina']}]\n{r['texto']}\n"

    contexto = contexto[:2200]

    prompt = f"""

INSTRUÇÕES:

- Responda exclusivamente com base no contexto.
- Não invente informações.
- Seja objetivo.
- Quando possível, fundamente sua resposta no próprio texto.

CONTEXTO:

{contexto}

PERGUNTA:

{pergunta}

RESPOSTA:
"""

    resposta = llm(prompt)[0]["generated_text"].strip()

    return {
        "resposta": resposta,
        "paginas": sorted(set(paginas_utilizadas))
    }

print("="*60)
print("AGENTE DE IA PARA DOCUMENTOS PDF")
print("Digite 'sair' para encerrar.")
print("="*60)

while True:

    pergunta = input("\nPergunta: ")

    if pergunta.lower() == "sair":
        print("Sessão encerrada.")
        break

    resultado = responder(pergunta)

    print("\nResposta:\n")
    print(resultado["resposta"])

    if resultado["paginas"]:
        paginas = ", ".join(map(str, resultado["paginas"]))
        print(f"\nPáginas consultadas: {paginas}")